INSERT INTO BoardSpaceTheme (ThemeId,BoardSpaceId,BoardSpaceName) VALUES
(2,1,'Lightning Pass'),
(2,2,'Gorilla Falls Exploration Trail'),
(2,3,'Magical Moments'),
(2,4,'Wilderness Explorers'),
(2,5,'Food Tax'),
(2,6,'Animal Kingdom'),
(2,7,'Na''vi River Journey'),
(2,8,'Magical Moments'),
(2,9,'Kilimanjaro Safari'),
(2,10,'Avatar Flight of Passage'),
(2,11,'Disney Jail'),
(2,12,'Tower of Terror'),
(2,13,'Fantasmic Fireworks'),
(2,14,'Millenium Falcon'),
(2,15,'Toy Story Mania'),
(2,16,'Hollywood Studios'),
(2,17,'Slinky Dog'),
(2,18,'Magical Moments'),
(2,19,'Rock n Roll Coaster'),
(2,20,'Micky & Minnie RR'),
(2,21,'Micky Sighting'),
(2,22,'It''s a Small World'),
(2,23,'Magical Moments'),
(2,24,'Tomorrowland Speedway'),
(2,25,'Haunted Mansion'),
(2,26,'Magic Kingdom'),
(2,27,'Peter Pan'),
(2,28,'Seven Dwarf Mine Train'),
(2,29,'Happily Ever After Fireworks'),
(2,30,'Tiana''s Bayou'),
(2,31,'Go To Disney Jail'),
(2,32,'The Seas With Nemo'),
(2,33,'Sorin'' Around the World'),
(2,34,'Magical Moments'),
(2,35,'Frozen'),
(2,36,'Epcot'),
(2,37,'Magical Moments'),
(2,38,'Remy''s Ratatouille'),
(2,39,'Vacation Tax'),
(2,40,'Guardians of the Galaxy');

