
INSERT INTO ThemeCard (CardId,ThemeId,CardDescription) VALUES
(1,1,'Advance to Boardwalk.'),
(2,1,'Advance to Go (Collect $200).'),
(3,1,'Advance to Illinois Avenue. If you pass Go, collect $200.'),
(4,1,'Advance to St. Charles Place. If you pass Go, collect $200.'),
(5,1,'Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled.'),
(6,1,'Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled.'),
(7,1,'Advance token to nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.'),
(8,1,'Bank pays you dividend of $50.'),
(9,1,'Get Out of Jail Free'),
(10,1,'Go Back 3 Spaces.'),
(11,1,'Go to Jail. Go directly to Jail, do not pass Go, do not collect $200.'),
(12,1,'Make general repairs on all your property. For each house pay $25. For each hotel pay $100.'),
(13,1,'Speeding fine $15.'),
(14,1,'Take a trip to Reading Railroad. If you pass Go, collect $200.'),
(15,1,'You have been elected Chairman of the Board. Pay each player $50.'),
(16,1,'Your building loan matures. Collect $150'),
(17,1,'Advance to Go (Collect $200)'),
(18,1,'Bank error in your favor. Collect $200'),
(19,1,'Doctor''s fee. Pay $50'),
(20,1,'From sale of stock you get $50'),
(21,1,'Get Out of Jail Free'),
(22,1,'Go to Jail. Go directly to jail, do not pass Go, do not collect $200'),
(23,1,'Holiday fund matures. Receive $100'),
(24,1,'Income tax refund. Collect $20'),
(25,1,'It is your birthday. Collect $10 from every player'),
(26,1,'Life insurance matures. Collect $100'),
(27,1,'Pay hospital fees of $100'),
(28,1,'Pay school fees of $50'),
(29,1,'Receive $25 consultancy fee'),
(30,1,'You are assessed for street repair. $40 per house. $115 per hotel'),
(31,1,'You have won second prize in a beauty contest. Collect $10'),
(32,1,'You inherit $100');

